apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabiane-data-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
spec:
  tls:
    - hosts:
        - sabiane-data-api.dev.insee.io
  rules:
    - host: sabiane-data-api.dev.insee.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabiane-data-api
                port:
                  number: 8080
