postgresql:
  global:
    postgresql:
      existingSecret: postgresql-secret
  postgresqlDatabase: poc
  postgresqlExtendedConf: 
    maxConnections: 300
    sharedBuffers: 2000MB
  metrics:
    enabled: true
  resources:
    limits:
      cpu: "2.2"
      memory: "8.2Gi"
    requests:
      cpu: "2"
      memory: "8Gi"
  primary:
    tolerations:
      - key: "metallica"
        operator: "Equal"
        value: "perf"
        effect: "NoSchedule"
    # extraInitContainers:
    #   - name: import-dump
    #     image: busybox
    #     command:
    #       [
    #         "wget",
    #         "https://changeme/backup.sql",
    #         "--output-document=/import/backup.sql",
    #       ]
    #     volumeMounts:
    #       - mountPath: /import
    #         name: import-volume

    # extraVolumes:
    #   - name: import-volume
    #     emptyDir: {}

    # extraVolumeMounts:
    #   - name: import-volume
    #     mountPath: "/docker-entrypoint-initdb.d"