grafana:
  persistence:
    enabled: true
  rbac:
    pspEnabled: false
    namespaced: true
  ingress:
    enabled: true
    hosts: 
      - grafana-poc-metallica.dev.insee.io
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      k6:
        gnetId: 2587
        revision: 3
        datasource: InfluxDB
      k6-2:
        #gnetId: 13719
        #revision: 5
        #datasource: InfluxDB
        url: https://minio.lab.sspcloud.fr/io1h80/dashboard/k6-2.json #Forked from gnetId 13719 revision 5
        token: ''
      micrometer:
        gnetId: 4701
        revision: 9
        datasource: Prometheus
      mongodb:
        gnetId: 2583
        revision: 2
        datasource: Prometheus
      postgresql:
        gnetId: 9628
        revision: 7
        datasource: Prometheus
  datasources:
    datasources.yaml:
      datasources:
        - name: InfluxDB
          type: influxdb
          database: k6
          url: http://my-influxdb:8086
        - name: Prometheus
          type: prometheus
          url: http://my-prometheus-server
  tolerations:   
    - key: "metallica"
      operator: "Equal"
      value: "perf"
      effect: "NoSchedule"

